//package com.companyname.one.domain;
//
//import java.io.Serializable;
//import java.util.Date;
//
///**
// * Model class of comments.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Comments implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** commentsId. */
//	private Integer commentsid;
//
//	/** lessons. */
//	private Lessons lessons;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** message. */
//	private String message;
//
//	/** date. */
//	private Date date;
//
//	/** modifiedDate. */
//	private Date modifieddate;
//
//	/**
//	 * Constructor.
//	 */
//	public Comments() {
//	}
//
//	/**
//	 * Set the commentsId.
//	 * 
//	 * @param commentsid
//	 *            commentsId
//	 */
//	public void setCommentsid(Integer commentsid) {
//		this.commentsid = commentsid;
//	}
//
//	/**
//	 * Get the commentsId.
//	 * 
//	 * @return commentsId
//	 */
//	public Integer getCommentsid() {
//		return this.commentsid;
//	}
//
//	/**
//	 * Set the lessons.
//	 * 
//	 * @param lessons
//	 *            lessons
//	 */
//	public void setLessons(Lessons lessons) {
//		this.lessons = lessons;
//	}
//
//	/**
//	 * Get the lessons.
//	 * 
//	 * @return lessons
//	 */
//	public Lessons getLessons() {
//		return this.lessons;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the message.
//	 * 
//	 * @param message
//	 *            message
//	 */
//	public void setMessage(String message) {
//		this.message = message;
//	}
//
//	/**
//	 * Get the message.
//	 * 
//	 * @return message
//	 */
//	public String getMessage() {
//		return this.message;
//	}
//
//	/**
//	 * Set the date.
//	 * 
//	 * @param date
//	 *            date
//	 */
//	public void setDate(Date date) {
//		this.date = date;
//	}
//
//	/**
//	 * Get the date.
//	 * 
//	 * @return date
//	 */
//	public Date getDate() {
//		return this.date;
//	}
//
//	/**
//	 * Set the modifiedDate.
//	 * 
//	 * @param modifieddate
//	 *            modifiedDate
//	 */
//	public void setModifieddate(Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//	/**
//	 * Get the modifiedDate.
//	 * 
//	 * @return modifiedDate
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((commentsid == null) ? 0 : commentsid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Comments other = (Comments) obj;
//		if (commentsid == null) {
//			if (other.commentsid != null) {
//				return false;
//			}
//		} else if (!commentsid.equals(other.commentsid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
