//package com.companyname.learn;
//
//import java.io.Serializable;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Model class of Courses.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Courses implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** coursesId. */
//	private Integer coursesid;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** useraccount. */
//	private Useraccount studentiduseraccount;
//
//	/** languagesId. */
//	private Integer languagesid;
//
//	/** courseName. */
//	private String coursename;
//
//	/** video. */
//	private String video;
//
//	/** amount. */
//	private Integer amount;
//
//	/** receivedDate. */
//	private Date receiveddate;
//
//	/** date. */
//	private Date date;
//
//	/** modifiedDate. */
//	private Date modifieddate;
//
//	/** The set of exam. */
//	private Set<Exam> examSet;
//
//	/** The set of languages. */
//	private Set<Languages> languagesSet;
//
//	/**
//	 * Constructor.
//	 */
//	public Courses() {
//		this.examSet = new HashSet<Exam>();
//		this.languagesSet = new HashSet<Languages>();
//	}
//
//	/**
//	 * Set the coursesId.
//	 * 
//	 * @param coursesid
//	 *            coursesId
//	 */
//	public void setCoursesid(Integer coursesid) {
//		this.coursesid = coursesid;
//	}
//
//	/**
//	 * Get the coursesId.
//	 * 
//	 * @return coursesId
//	 */
//	public Integer getCoursesid() {
//		return this.coursesid;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param studentiduseraccount
//	 *            useraccount
//	 */
//	public void setStudentiduseraccount(Useraccount studentiduseraccount) {
//		this.studentiduseraccount = studentiduseraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getStudentiduseraccount() {
//		return this.studentiduseraccount;
//	}
//
//	/**
//	 * Set the languagesId.
//	 * 
//	 * @param languagesid
//	 *            languagesId
//	 */
//	public void setLanguagesid(Integer languagesid) {
//		this.languagesid = languagesid;
//	}
//
//	/**
//	 * Get the languagesId.
//	 * 
//	 * @return languagesId
//	 */
//	public Integer getLanguagesid() {
//		return this.languagesid;
//	}
//
//	/**
//	 * Set the courseName.
//	 * 
//	 * @param coursename
//	 *            courseName
//	 */
//	public void setCoursename(String coursename) {
//		this.coursename = coursename;
//	}
//
//	/**
//	 * Get the courseName.
//	 * 
//	 * @return courseName
//	 */
//	public String getCoursename() {
//		return this.coursename;
//	}
//
//	/**
//	 * Set the video.
//	 * 
//	 * @param video
//	 *            video
//	 */
//	public void setVideo(String video) {
//		this.video = video;
//	}
//
//	/**
//	 * Get the video.
//	 * 
//	 * @return video
//	 */
//	public String getVideo() {
//		return this.video;
//	}
//
//	/**
//	 * Set the amount.
//	 * 
//	 * @param amount
//	 *            amount
//	 */
//	public void setAmount(Integer amount) {
//		this.amount = amount;
//	}
//
//	/**
//	 * Get the amount.
//	 * 
//	 * @return amount
//	 */
//	public Integer getAmount() {
//		return this.amount;
//	}
//
//	/**
//	 * Set the receivedDate.
//	 * 
//	 * @param receiveddate
//	 *            receivedDate
//	 */
//	public void setReceiveddate(Date receiveddate) {
//		this.receiveddate = receiveddate;
//	}
//
//	/**
//	 * Get the receivedDate.
//	 * 
//	 * @return receivedDate
//	 */
//	public Date getReceiveddate() {
//		return this.receiveddate;
//	}
//
//	/**
//	 * Set the date.
//	 * 
//	 * @param date
//	 *            date
//	 */
//	public void setDate(Date date) {
//		this.date = date;
//	}
//
//	/**
//	 * Get the date.
//	 * 
//	 * @return date
//	 */
//	public Date getDate() {
//		return this.date;
//	}
//
//	/**
//	 * Set the modifiedDate.
//	 * 
//	 * @param modifieddate
//	 *            modifiedDate
//	 */
//	public void setModifieddate(Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//	/**
//	 * Get the modifiedDate.
//	 * 
//	 * @return modifiedDate
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//	}
//
//	/**
//	 * Set the set of the exam.
//	 * 
//	 * @param examSet
//	 *            The set of exam
//	 */
//	public void setExamSet(Set<Exam> examSet) {
//		this.examSet = examSet;
//	}
//
//	/**
//	 * Add the exam.
//	 * 
//	 * @param exam
//	 *            exam
//	 */
//	public void addExam(Exam exam) {
//		this.examSet.add(exam);
//	}
//
//	/**
//	 * Get the set of the exam.
//	 * 
//	 * @return The set of exam
//	 */
//	public Set<Exam> getExamSet() {
//		return this.examSet;
//	}
//
//	/**
//	 * Set the set of the languages.
//	 * 
//	 * @param languagesSet
//	 *            The set of languages
//	 */
//	public void setLanguagesSet(Set<Languages> languagesSet) {
//		this.languagesSet = languagesSet;
//	}
//
//	/**
//	 * Add the languages.
//	 * 
//	 * @param languages
//	 *            languages
//	 */
//	public void addLanguages(Languages languages) {
//		this.languagesSet.add(languages);
//	}
//
//	/**
//	 * Get the set of the languages.
//	 * 
//	 * @return The set of languages
//	 */
//	public Set<Languages> getLanguagesSet() {
//		return this.languagesSet;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((coursesid == null) ? 0 : coursesid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Courses other = (Courses) obj;
//		if (coursesid == null) {
//			if (other.coursesid != null) {
//				return false;
//			}
//		} else if (!coursesid.equals(other.coursesid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
