//package com.companyname.one.domain;
//
//import java.io.Serializable;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Model class of Courses.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Courses implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** coursesId. */
//	private Integer coursesid;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** useraccount. */
//	private Useraccount studentiduseraccount;
//
//	/** languages. */
//	private Languages languages;
//
//	/** type. */
//	private Object type;
//
//	/** amount. */
//	private Integer amount;
//
//	/** receivedDate. */
//	private Date receiveddate;
//
//	/** date. */
//	private Date date;
//
//	/** modifiedDate. */
//	private Date modifieddate;
//
//	/** The set of examAns. */
//	private Set<Examans> examansSet;
//
//	/**
//	 * Constructor.
//	 */
//	public Courses() {
//		this.examansSet = new HashSet<Examans>();
//	}
//
//	/**
//	 * Set the coursesId.
//	 * 
//	 * @param coursesid
//	 *            coursesId
//	 */
//	public void setCoursesid(Integer coursesid) {
//		this.coursesid = coursesid;
//	}
//
//	/**
//	 * Get the coursesId.
//	 * 
//	 * @return coursesId
//	 */
//	public Integer getCoursesid() {
//		return this.coursesid;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param studentiduseraccount
//	 *            useraccount
//	 */
//	public void setStudentiduseraccount(Useraccount studentiduseraccount) {
//		this.studentiduseraccount = studentiduseraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getStudentiduseraccount() {
//		return this.studentiduseraccount;
//	}
//
//	/**
//	 * Set the languages.
//	 * 
//	 * @param languages
//	 *            languages
//	 */
//	public void setLanguages(Languages languages) {
//		this.languages = languages;
//	}
//
//	/**
//	 * Get the languages.
//	 * 
//	 * @return languages
//	 */
//	public Languages getLanguages() {
//		return this.languages;
//	}
//
//	/**
//	 * Set the type.
//	 * 
//	 * @param type
//	 *            type
//	 */
//	public void setType(Object type) {
//		this.type = type;
//	}
//
//	/**
//	 * Get the type.
//	 * 
//	 * @return type
//	 */
//	public Object getType() {
//		return this.type;
//	}
//
//	/**
//	 * Set the amount.
//	 * 
//	 * @param amount
//	 *            amount
//	 */
//	public void setAmount(Integer amount) {
//		this.amount = amount;
//	}
//
//	/**
//	 * Get the amount.
//	 * 
//	 * @return amount
//	 */
//	public Integer getAmount() {
//		return this.amount;
//	}
//
//	/**
//	 * Set the receivedDate.
//	 * 
//	 * @param receiveddate
//	 *            receivedDate
//	 */
//	public void setReceiveddate(Date receiveddate) {
//		this.receiveddate = receiveddate;
//	}
//
//	/**
//	 * Get the receivedDate.
//	 * 
//	 * @return receivedDate
//	 */
//	public Date getReceiveddate() {
//		return this.receiveddate;
//	}
//
//	/**
//	 * Set the date.
//	 * 
//	 * @param date
//	 *            date
//	 */
//	public void setDate(Date date) {
//		this.date = date;
//	}
//
//	/**
//	 * Get the date.
//	 * 
//	 * @return date
//	 */
//	public Date getDate() {
//		return this.date;
//	}
//
//	/**
//	 * Set the modifiedDate.
//	 * 
//	 * @param modifieddate
//	 *            modifiedDate
//	 */
//	public void setModifieddate(Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//	/**
//	 * Get the modifiedDate.
//	 * 
//	 * @return modifiedDate
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//	}
//
//	/**
//	 * Set the set of the examAns.
//	 * 
//	 * @param examansSet
//	 *            The set of examAns
//	 */
//	public void setExamansSet(Set<Examans> examansSet) {
//		this.examansSet = examansSet;
//	}
//
//	/**
//	 * Add the examAns.
//	 * 
//	 * @param examans
//	 *            examAns
//	 */
//	public void addExamans(Examans examans) {
//		this.examansSet.add(examans);
//	}
//
//	/**
//	 * Get the set of the examAns.
//	 * 
//	 * @return The set of examAns
//	 */
//	public Set<Examans> getExamansSet() {
//		return this.examansSet;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((coursesid == null) ? 0 : coursesid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Courses other = (Courses) obj;
//		if (coursesid == null) {
//			if (other.coursesid != null) {
//				return false;
//			}
//		} else if (!coursesid.equals(other.coursesid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
