//package com.companyname.learn;
//
//import java.io.Serializable;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Model class of exam.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Exam implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** examId. */
//	private Integer examid;
//
//	/** examLink. */
//	private String examlink;
//
//	/** examMark. */
//	private Integer exammark;
//
//	/** Courses. */
//	private Courses courses;
//
//	/** examFee. */
//	private Examfee examfee;
//
//	/** The set of certificate. */
//	private Set<Certificate> certificateSet;
//
//	/**
//	 * Constructor.
//	 */
//	public Exam() {
//		this.certificateSet = new HashSet<Certificate>();
//	}
//
//	/**
//	 * Set the examId.
//	 * 
//	 * @param examid
//	 *            examId
//	 */
//	public void setExamid(Integer examid) {
//		this.examid = examid;
//	}
//
//	/**
//	 * Get the examId.
//	 * 
//	 * @return examId
//	 */
//	public Integer getExamid() {
//		return this.examid;
//	}
//
//	/**
//	 * Set the examLink.
//	 * 
//	 * @param examlink
//	 *            examLink
//	 */
//	public void setExamlink(String examlink) {
//		this.examlink = examlink;
//	}
//
//	/**
//	 * Get the examLink.
//	 * 
//	 * @return examLink
//	 */
//	public String getExamlink() {
//		return this.examlink;
//	}
//
//	/**
//	 * Set the examMark.
//	 * 
//	 * @param exammark
//	 *            examMark
//	 */
//	public void setExammark(Integer exammark) {
//		this.exammark = exammark;
//	}
//
//	/**
//	 * Get the examMark.
//	 * 
//	 * @return examMark
//	 */
//	public Integer getExammark() {
//		return this.exammark;
//	}
//
//	/**
//	 * Set the Courses.
//	 * 
//	 * @param courses
//	 *            Courses
//	 */
//	public void setCourses(Courses courses) {
//		this.courses = courses;
//	}
//
//	/**
//	 * Get the Courses.
//	 * 
//	 * @return Courses
//	 */
//	public Courses getCourses() {
//		return this.courses;
//	}
//
//	/**
//	 * Set the examFee.
//	 * 
//	 * @param examfee
//	 *            examFee
//	 */
//	public void setExamfee(Examfee examfee) {
//		this.examfee = examfee;
//	}
//
//	/**
//	 * Get the examFee.
//	 * 
//	 * @return examFee
//	 */
//	public Examfee getExamfee() {
//		return this.examfee;
//	}
//
//	/**
//	 * Set the set of the certificate.
//	 * 
//	 * @param certificateSet
//	 *            The set of certificate
//	 */
//	public void setCertificateSet(Set<Certificate> certificateSet) {
//		this.certificateSet = certificateSet;
//	}
//
//	/**
//	 * Add the certificate.
//	 * 
//	 * @param certificate
//	 *            certificate
//	 */
//	public void addCertificate(Certificate certificate) {
//		this.certificateSet.add(certificate);
//	}
//
//	/**
//	 * Get the set of the certificate.
//	 * 
//	 * @return The set of certificate
//	 */
//	public Set<Certificate> getCertificateSet() {
//		return this.certificateSet;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((examid == null) ? 0 : examid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Exam other = (Exam) obj;
//		if (examid == null) {
//			if (other.examid != null) {
//				return false;
//			}
//		} else if (!examid.equals(other.examid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
