//package com.companyname.learn;
//
//import java.io.Serializable;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Model class of examFee.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Examfee implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** examFeeId. */
//	private Integer examfeeid;
//
//	/** feeAmount. */
//	private Integer feeamount;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** The set of exam. */
//	private Set<Exam> examSet;
//
//	/**
//	 * Constructor.
//	 */
//	public Examfee() {
//		this.examSet = new HashSet<Exam>();
//	}
//
//	/**
//	 * Set the examFeeId.
//	 * 
//	 * @param examfeeid
//	 *            examFeeId
//	 */
//	public void setExamfeeid(Integer examfeeid) {
//		this.examfeeid = examfeeid;
//	}
//
//	/**
//	 * Get the examFeeId.
//	 * 
//	 * @return examFeeId
//	 */
//	public Integer getExamfeeid() {
//		return this.examfeeid;
//	}
//
//	/**
//	 * Set the feeAmount.
//	 * 
//	 * @param feeamount
//	 *            feeAmount
//	 */
//	public void setFeeamount(Integer feeamount) {
//		this.feeamount = feeamount;
//	}
//
//	/**
//	 * Get the feeAmount.
//	 * 
//	 * @return feeAmount
//	 */
//	public Integer getFeeamount() {
//		return this.feeamount;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the set of the exam.
//	 * 
//	 * @param examSet
//	 *            The set of exam
//	 */
//	public void setExamSet(Set<Exam> examSet) {
//		this.examSet = examSet;
//	}
//
//	/**
//	 * Add the exam.
//	 * 
//	 * @param exam
//	 *            exam
//	 */
//	public void addExam(Exam exam) {
//		this.examSet.add(exam);
//	}
//
//	/**
//	 * Get the set of the exam.
//	 * 
//	 * @return The set of exam
//	 */
//	public Set<Exam> getExamSet() {
//		return this.examSet;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((examfeeid == null) ? 0 : examfeeid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Examfee other = (Examfee) obj;
//		if (examfeeid == null) {
//			if (other.examfeeid != null) {
//				return false;
//			}
//		} else if (!examfeeid.equals(other.examfeeid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
