//package com.companyname.one.domain;
//
//import java.io.Serializable;
//import java.util.Date;
//
///**
// * Model class of examAns.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Examans implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** examId. */
//	private Integer examid;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** Courses. */
//	private Courses courses;
//
//	/** pdf. */
//	private String pdf;
//
//	/** examMark. */
//	private Integer exammark;
//
//	/** date. */
//	private Date date;
//
//	/** status. */
//	private Object status;
//
//	/**
//	 * Constructor.
//	 */
//	public Examans() {
//	}
//
//	/**
//	 * Set the examId.
//	 * 
//	 * @param examid
//	 *            examId
//	 */
//	public void setExamid(Integer examid) {
//		this.examid = examid;
//	}
//
//	/**
//	 * Get the examId.
//	 * 
//	 * @return examId
//	 */
//	public Integer getExamid() {
//		return this.examid;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the Courses.
//	 * 
//	 * @param courses
//	 *            Courses
//	 */
//	public void setCourses(Courses courses) {
//		this.courses = courses;
//	}
//
//	/**
//	 * Get the Courses.
//	 * 
//	 * @return Courses
//	 */
//	public Courses getCourses() {
//		return this.courses;
//	}
//
//	/**
//	 * Set the pdf.
//	 * 
//	 * @param pdf
//	 *            pdf
//	 */
//	public void setPdf(String pdf) {
//		this.pdf = pdf;
//	}
//
//	/**
//	 * Get the pdf.
//	 * 
//	 * @return pdf
//	 */
//	public String getPdf() {
//		return this.pdf;
//	}
//
//	/**
//	 * Set the examMark.
//	 * 
//	 * @param exammark
//	 *            examMark
//	 */
//	public void setExammark(Integer exammark) {
//		this.exammark = exammark;
//	}
//
//	/**
//	 * Get the examMark.
//	 * 
//	 * @return examMark
//	 */
//	public Integer getExammark() {
//		return this.exammark;
//	}
//
//	/**
//	 * Set the date.
//	 * 
//	 * @param date
//	 *            date
//	 */
//	public void setDate(Date date) {
//		this.date = date;
//	}
//
//	/**
//	 * Get the date.
//	 * 
//	 * @return date
//	 */
//	public Date getDate() {
//		return this.date;
//	}
//
//	/**
//	 * Set the status.
//	 * 
//	 * @param status
//	 *            status
//	 */
//	public void setStatus(Object status) {
//		this.status = status;
//	}
//
//	/**
//	 * Get the status.
//	 * 
//	 * @return status
//	 */
//	public Object getStatus() {
//		return this.status;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((examid == null) ? 0 : examid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Examans other = (Examans) obj;
//		if (examid == null) {
//			if (other.examid != null) {
//				return false;
//			}
//		} else if (!examid.equals(other.examid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
