//package com.companyname.learn;
//
//import java.io.Serializable;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Model class of languages.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Languages implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** languagesId. */
//	private Integer languagesid;
//
//	/** name. */
//	private String name;
//
//	/** amount. */
//	private Integer amount;
//
//	/** Courses. */
//	private Courses courses;
//
//	/** useraccount. */
//	private Useraccount studentiduseraccount;
//
//	/** The set of certificate. */
//	private Set<Certificate> certificateSet;
//
//	/** The set of lessons. */
//	private Set<Lessons> lessonsSet;
//
//	/**
//	 * Constructor.
//	 */
//	public Languages() {
//		this.certificateSet = new HashSet<Certificate>();
//		this.lessonsSet = new HashSet<Lessons>();
//	}
//
//	/**
//	 * Set the languagesId.
//	 * 
//	 * @param languagesid
//	 *            languagesId
//	 */
//	public void setLanguagesid(Integer languagesid) {
//		this.languagesid = languagesid;
//	}
//
//	/**
//	 * Get the languagesId.
//	 * 
//	 * @return languagesId
//	 */
//	public Integer getLanguagesid() {
//		return this.languagesid;
//	}
//
//	/**
//	 * Set the name.
//	 * 
//	 * @param name
//	 *            name
//	 */
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	/**
//	 * Get the name.
//	 * 
//	 * @return name
//	 */
//	public String getName() {
//		return this.name;
//	}
//
//	/**
//	 * Set the amount.
//	 * 
//	 * @param amount
//	 *            amount
//	 */
//	public void setAmount(Integer amount) {
//		this.amount = amount;
//	}
//
//	/**
//	 * Get the amount.
//	 * 
//	 * @return amount
//	 */
//	public Integer getAmount() {
//		return this.amount;
//	}
//
//	/**
//	 * Set the Courses.
//	 * 
//	 * @param courses
//	 *            Courses
//	 */
//	public void setCourses(Courses courses) {
//		this.courses = courses;
//	}
//
//	/**
//	 * Get the Courses.
//	 * 
//	 * @return Courses
//	 */
//	public Courses getCourses() {
//		return this.courses;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param studentiduseraccount
//	 *            useraccount
//	 */
//	public void setStudentiduseraccount(Useraccount studentiduseraccount) {
//		this.studentiduseraccount = studentiduseraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getStudentiduseraccount() {
//		return this.studentiduseraccount;
//	}
//
//	/**
//	 * Set the set of the certificate.
//	 * 
//	 * @param certificateSet
//	 *            The set of certificate
//	 */
//	public void setCertificateSet(Set<Certificate> certificateSet) {
//		this.certificateSet = certificateSet;
//	}
//
//	/**
//	 * Add the certificate.
//	 * 
//	 * @param certificate
//	 *            certificate
//	 */
//	public void addCertificate(Certificate certificate) {
//		this.certificateSet.add(certificate);
//	}
//
//	/**
//	 * Get the set of the certificate.
//	 * 
//	 * @return The set of certificate
//	 */
//	public Set<Certificate> getCertificateSet() {
//		return this.certificateSet;
//	}
//
//	/**
//	 * Set the set of the lessons.
//	 * 
//	 * @param lessonsSet
//	 *            The set of lessons
//	 */
//	public void setLessonsSet(Set<Lessons> lessonsSet) {
//		this.lessonsSet = lessonsSet;
//	}
//
//	/**
//	 * Add the lessons.
//	 * 
//	 * @param lessons
//	 *            lessons
//	 */
//	public void addLessons(Lessons lessons) {
//		this.lessonsSet.add(lessons);
//	}
//
//	/**
//	 * Get the set of the lessons.
//	 * 
//	 * @return The set of lessons
//	 */
//	public Set<Lessons> getLessonsSet() {
//		return this.lessonsSet;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((languagesid == null) ? 0 : languagesid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Languages other = (Languages) obj;
//		if (languagesid == null) {
//			if (other.languagesid != null) {
//				return false;
//			}
//		} else if (!languagesid.equals(other.languagesid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
