//package com.companyname.learn;
//
//import java.io.Serializable;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Model class of lessons.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Lessons implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** lessonsId. */
//	private Integer lessonsid;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** languages. */
//	private Languages languages;
//
//	/** youtube. */
//	private String youtube;
//
//	/** pdf. */
//	private String pdf;
//
//	/** date. */
//	private Date date;
//
//	/** modifiedDate. */
//	private Date modifieddate;
//
//	/** The set of comments. */
//	private Set<Comments> commentsSet;
//
//	/** The set of ratings. */
//	private Set<Ratings> ratingsSet;
//
//	/**
//	 * Constructor.
//	 */
//	public Lessons() {
//		this.commentsSet = new HashSet<Comments>();
//		this.ratingsSet = new HashSet<Ratings>();
//	}
//
//	/**
//	 * Set the lessonsId.
//	 * 
//	 * @param lessonsid
//	 *            lessonsId
//	 */
//	public void setLessonsid(Integer lessonsid) {
//		this.lessonsid = lessonsid;
//	}
//
//	/**
//	 * Get the lessonsId.
//	 * 
//	 * @return lessonsId
//	 */
//	public Integer getLessonsid() {
//		return this.lessonsid;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the languages.
//	 * 
//	 * @param languages
//	 *            languages
//	 */
//	public void setLanguages(Languages languages) {
//		this.languages = languages;
//	}
//
//	/**
//	 * Get the languages.
//	 * 
//	 * @return languages
//	 */
//	public Languages getLanguages() {
//		return this.languages;
//	}
//
//	/**
//	 * Set the youtube.
//	 * 
//	 * @param youtube
//	 *            youtube
//	 */
//	public void setYoutube(String youtube) {
//		this.youtube = youtube;
//	}
//
//	/**
//	 * Get the youtube.
//	 * 
//	 * @return youtube
//	 */
//	public String getYoutube() {
//		return this.youtube;
//	}
//
//	/**
//	 * Set the pdf.
//	 * 
//	 * @param pdf
//	 *            pdf
//	 */
//	public void setPdf(String pdf) {
//		this.pdf = pdf;
//	}
//
//	/**
//	 * Get the pdf.
//	 * 
//	 * @return pdf
//	 */
//	public String getPdf() {
//		return this.pdf;
//	}
//
//	/**
//	 * Set the date.
//	 * 
//	 * @param date
//	 *            date
//	 */
//	public void setDate(Date date) {
//		this.date = date;
//	}
//
//	/**
//	 * Get the date.
//	 * 
//	 * @return date
//	 */
//	public Date getDate() {
//		return this.date;
//	}
//
//	/**
//	 * Set the modifiedDate.
//	 * 
//	 * @param modifieddate
//	 *            modifiedDate
//	 */
//	public void setModifieddate(Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//	/**
//	 * Get the modifiedDate.
//	 * 
//	 * @return modifiedDate
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//	}
//
//	/**
//	 * Set the set of the comments.
//	 * 
//	 * @param commentsSet
//	 *            The set of comments
//	 */
//	public void setCommentsSet(Set<Comments> commentsSet) {
//		this.commentsSet = commentsSet;
//	}
//
//	/**
//	 * Add the comments.
//	 * 
//	 * @param comments
//	 *            comments
//	 */
//	public void addComments(Comments comments) {
//		this.commentsSet.add(comments);
//	}
//
//	/**
//	 * Get the set of the comments.
//	 * 
//	 * @return The set of comments
//	 */
//	public Set<Comments> getCommentsSet() {
//		return this.commentsSet;
//	}
//
//	/**
//	 * Set the set of the ratings.
//	 * 
//	 * @param ratingsSet
//	 *            The set of ratings
//	 */
//	public void setRatingsSet(Set<Ratings> ratingsSet) {
//		this.ratingsSet = ratingsSet;
//	}
//
//	/**
//	 * Add the ratings.
//	 * 
//	 * @param ratings
//	 *            ratings
//	 */
//	public void addRatings(Ratings ratings) {
//		this.ratingsSet.add(ratings);
//	}
//
//	/**
//	 * Get the set of the ratings.
//	 * 
//	 * @return The set of ratings
//	 */
//	public Set<Ratings> getRatingsSet() {
//		return this.ratingsSet;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((lessonsid == null) ? 0 : lessonsid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Lessons other = (Lessons) obj;
//		if (lessonsid == null) {
//			if (other.lessonsid != null) {
//				return false;
//			}
//		} else if (!lessonsid.equals(other.lessonsid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
