//package com.companyname.one.domain;
//
//import java.io.Serializable;
//import java.util.Date;
//
///**
// * Model class of ratings.
// * 
// * @author generated by ERMaster
// * @version $Id$
// */
//public class Ratings implements Serializable {
//
//	/** serialVersionUID. */
//	private static final long serialVersionUID = 1L;
//
//	/** ratingsId. */
//	private Integer ratingsid;
//
//	/** useraccount. */
//	private Useraccount useraccount;
//
//	/** lessons. */
//	private Lessons lessons;
//
//	/** rate. */
//	private Integer rate;
//
//	/** date. */
//	private Date date;
//
//	/** modifiedDate. */
//	private Date modifieddate;
//
//	/**
//	 * Constructor.
//	 */
//	public Ratings() {
//	}
//
//	/**
//	 * Set the ratingsId.
//	 * 
//	 * @param ratingsid
//	 *            ratingsId
//	 */
//	public void setRatingsid(Integer ratingsid) {
//		this.ratingsid = ratingsid;
//	}
//
//	/**
//	 * Get the ratingsId.
//	 * 
//	 * @return ratingsId
//	 */
//	public Integer getRatingsid() {
//		return this.ratingsid;
//	}
//
//	/**
//	 * Set the useraccount.
//	 * 
//	 * @param useraccount
//	 *            useraccount
//	 */
//	public void setUseraccount(Useraccount useraccount) {
//		this.useraccount = useraccount;
//	}
//
//	/**
//	 * Get the useraccount.
//	 * 
//	 * @return useraccount
//	 */
//	public Useraccount getUseraccount() {
//		return this.useraccount;
//	}
//
//	/**
//	 * Set the lessons.
//	 * 
//	 * @param lessons
//	 *            lessons
//	 */
//	public void setLessons(Lessons lessons) {
//		this.lessons = lessons;
//	}
//
//	/**
//	 * Get the lessons.
//	 * 
//	 * @return lessons
//	 */
//	public Lessons getLessons() {
//		return this.lessons;
//	}
//
//	/**
//	 * Set the rate.
//	 * 
//	 * @param rate
//	 *            rate
//	 */
//	public void setRate(Integer rate) {
//		this.rate = rate;
//	}
//
//	/**
//	 * Get the rate.
//	 * 
//	 * @return rate
//	 */
//	public Integer getRate() {
//		return this.rate;
//	}
//
//	/**
//	 * Set the date.
//	 * 
//	 * @param date
//	 *            date
//	 */
//	public void setDate(Date date) {
//		this.date = date;
//	}
//
//	/**
//	 * Get the date.
//	 * 
//	 * @return date
//	 */
//	public Date getDate() {
//		return this.date;
//	}
//
//	/**
//	 * Set the modifiedDate.
//	 * 
//	 * @param modifieddate
//	 *            modifiedDate
//	 */
//	public void setModifieddate(Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//	/**
//	 * Get the modifiedDate.
//	 * 
//	 * @return modifiedDate
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((ratingsid == null) ? 0 : ratingsid.hashCode());
//		return result;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj) {
//			return true;
//		}
//		if (obj == null) {
//			return false;
//		}
//		if (getClass() != obj.getClass()) {
//			return false;
//		}
//		Ratings other = (Ratings) obj;
//		if (ratingsid == null) {
//			if (other.ratingsid != null) {
//				return false;
//			}
//		} else if (!ratingsid.equals(other.ratingsid)) {
//			return false;
//		}
//		return true;
//	}
//
//}
